name: CMake build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: ['mpich', 'openmpi', 'intelmpi']
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}
    - name: Configure CMake
      run: cmake --preset release
    - name: Build
      run: cmake --build --preset release --parallel
    - name: Test
      run: ctest --preset release

